name: 'Install Octopus-CLI'
description: 'Installation of the Octopus CLI'

inputs:
  version:
    description: Version to install
    required: true
  api_key:
    description: API key for the Octopus Deploy server
    required: false
  server_url:
    description: Octopus Deploy server URL
    required: false

runs:
  using: composite
  steps:
  - run: go run installoctocli.go
    shell: bash